centre_formation_accueil:
    path:     /
    defaults: { _controller: CentreFormationBundle:Default:index }

centre_formation_liste_formateurs:
    path:     /formateurss
    defaults: { _controller: CentreFormationBundle:Default:formateurs }

centre_formation_ajout_formateur:
    path:     /formateurs/add
    defaults: { _controller: CentreFormationBundle:Default:addFormateur }