_accueil:
    path: /accueil/
    defaults: { _controller: CentreFormationBundle:Main:accueil }

_formateurs:
    path: /formateurs/
    defaults: { _controller: CentreFormationBundle:Formateur:show }

_formateurs_add:
    path: /formateurs/add/
    defaults: { _controller: CentreFormationBundle:Formateur:add }

_formateurs_edit:
    path: /formateurs/edit/{id}
    defaults: { _controller: CentreFormationBundle:Formateur:edit}

_formateurs_delete:
    path: /formateurs/delete/{id}
    defaults: { _controller: CentreFormationBundle:Formateur:delete}
    methods: POST

_formations:
    path: /formations/
    defaults: { _controller: CentreFormationBundle:Formation:show }

_formations_add:
    path: /formations/add/
    defaults: { _controller: CentreFormationBundle:Formation:add }

_formations_edit:
    path: /formations/edit/{id}
    defaults: { _controller: CentreFormationBundle:Formation:edit}

_formations_delete:
    path: /formations/delete/{id}
    defaults: { _controller: CentreFormationBundle:Formation:delete}
    methods: POST