_accueil:
    path:     /accueil/
    defaults: { _controller: CentreFormationBundle:Main:accueil }

_formateurs:
    path:     /formateurs/
    defaults: { _controller: CentreFormationBundle:Formateur:liste }

_formateurs_add:
    path:     /formateurs/add/
    defaults: { _controller: CentreFormationBundle:Formateur:add }